{{- if and .Values.mongodb.install .Values.mongodb.persistent }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ .Values.appName }}-mongodb"
  labels:
    app: "{{ .Values.appName }}"
    container: mongodb
    group: microcks
  {{- with .Values.mongodb.pvcAnnotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mongodb.volumeSize }}
  {{- if hasKey .Values.mongodb "storageClassName" }}
  storageClassName: {{ .Values.mongodb.storageClassName }}
  {{- end }}
{{- end }}
{{- if and .Values.keycloak.install .Values.keycloak.persistent }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ .Values.appName }}-keycloak-postgresql"
  labels:
    app: "{{ .Values.appName }}"
    container: keycloak-postgresql
    group: microcks
  {{- with .Values.keycloak.pvcAnnotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.keycloak.volumeSize }}
  {{- if hasKey .Values.keycloak "storageClassName" }}
  storageClassName: {{ .Values.keycloak.storageClassName }}
  {{- end }}
{{- end }}